[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["server_cert.pem","server_key.pem"]
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"
